version: "3.9"
services:
  php-fpm:
    depends_on:
      - db

  db:
    hostname: "${ROLL_ENV_NAME}-mariadb"
    image: ${ROLL_IMAGE_REPOSITORY}/mariadb:${MARIADB_VERSION:-10.4}-dev
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-app}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-app}
      - MYSQL_USER=${MYSQL_USER:-app}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-app}
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
