name: Docker Image MySQL DEV
on:
  push:
    paths:
      - images/.trigger
      - images/mysql/**
      - .github/workflows/*mysql*

jobs:
  mysql8:
    name: MySQL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "8.0"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/mysql/8.0
          platforms: linux/amd64,linux/arm64
          build-args: MYSQL_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/alpha' && !env.ACT }}
          tags: docker.io/rollupdev/mysql:${{ matrix.version }}-dev

  mysql7min:
    name: MySQL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "5.6"
          - "5.7"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/mysql/5.x
          platforms: linux/amd64
          build-args: MYSQL_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/alpha' && !env.ACT }}
          tags: docker.io/rollupdev/mysql:${{ matrix.version }}-dev
