name: Docker Image MailHog
on:
  push:
    paths:
      - images/.trigger
      - images/mailhog/**
      - .github/workflows/*mailhog*

jobs:
  mailhog:
    name: MailHog
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.0"

    steps:
      - run: sudo chown runner:docker /var/run/docker.sock
        if: ${{ env.ACT }}
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v2
        with:
          context: images/mailhog
          platforms: linux/amd64,linux/arm64
          build-args: MAILHOG_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/rollupdev/mailhog:${{ matrix.version }}
