name: Docker Image Elasticsearch
on:
  push:
    paths:
      - images/.trigger
      - images/elasticsearch/**
      - .github/workflows/*elasticsearch*

jobs:
  elasticsearch:
    name: Elasticsearch
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "7.16"
          - "7.17"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    steps:

      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          ES_VERSION=$(
            docker run --rm gcr.io/go-containerregistry/crane:v0.8.0 ls elasticsearch \
            | egrep "^${ESCAPED_VERSION}\.[0-9]+\$" | sort -Vr | head -n1
          )
          echo "ES_VERSION=${ES_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/elasticsearch
          platforms: linux/amd64,linux/arm64
          build-args: ES_VERSION=${{ env.ES_VERSION }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/rollupdev/elasticsearch:${{ matrix.version }}
