name: Docker Image OpenSearch DEV
on:
  push:
    paths:
      - images/.trigger
      - images/opensearch/**
      - .github/workflows/*opensearch*

jobs:
  opensearch-dev:
    name: OpenSearch DEV
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "2.1"
          - "2.2"
          - "2.3"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          OPENSEARCH_VERSION=$(
            docker run --rm gcr.io/go-containerregistry/crane:v0.8.0 ls docker.io/opensearchproject/opensearch \
            | egrep "^${ESCAPED_VERSION}\.[0-9]+\$" | sort -Vr | head -n1
          )
          echo "OPENSEARCH_VERSION=${OPENSEARCH_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/opensearch
          platforms: linux/amd64,linux/arm64
          build-args: OPENSEARCH_VERSION=${{ env.OPENSEARCH_VERSION }}
          push: ${{ github.ref == 'refs/heads/alpha' && !env.ACT }}
          tags: docker.io/rollupdev/opensearch:${{ matrix.version }}-dev
