name: Docker Image RabbitMQ
on:
  push:
    paths:
      - images/.trigger
      - images/rabbitmq/**
      - .github/workflows/*rabbitmq*

jobs:
  rabbitmq:
    name: RabbitMQ
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "3.7"
          - "3.8"
          - "3.9"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/rabbitmq
          platforms: linux/amd64,linux/arm64
          build-args: RABBITMQ_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/rollupdev/rabbitmq:${{ matrix.version }}
