name: Docker Image Startpage DEV
on:
  push:
    paths:
      - images/.trigger
      - images/startpage/**
      - .github/workflows/*startpage*

jobs:
  startpage-dev:
    name: Startpage DEV
    runs-on: ubuntu-latest

    steps:

      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/startpage
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/alpha' && !env.ACT }}
          tags: docker.io/rollupdev/startpage:dev
