name: Docker Image MariaDB
on:
  push:
    paths:
      - images/.trigger
      - images/mariadb/**
      - .github/workflows/*mariadb*

jobs:
  mariadb:
    name: MariaDB
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "10.5"
          - "10.6"
          - "10.7"
          - "10.8"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/mariadb
          platforms: linux/amd64,linux/arm64
          build-args: MARIADB_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/rollupdev/mariadb:${{ matrix.version }}
