name: Docker Image Redis DEV
on:
  push:
    paths:
      - images/.trigger
      - images/redis/**
      - .github/workflows/*redis*

jobs:
  redis-dev:
    name: Redis DEV
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - from: "5-buster"
            tag: "5.0"
          - from: "6-bullseye"
            tag: "6.0"
          - from: "6.2-bullseye"
            tag: "6.2"
          - from: "7-bullseye"
            tag: "7.0"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/redis
          platforms: linux/amd64,linux/arm64
          build-args: REDIS_VERSION=${{ matrix.version.from }}
          push: ${{ github.ref == 'refs/heads/alpha' && !env.ACT }}
          tags: docker.io/rollupdev/redis:${{ matrix.version.tag }}-dev
