name: Docker Image Nginx
on:
  push:
    paths:
      - images/.trigger
      - images/nginx/**
      - .github/workflows/*nginx*

jobs:
  nginx:
    name: Nginx
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.16"
#          - "1.17"
#          - "1.18"
#          - "1.19"
#          - "1.20"
#          - "1.21"

    steps:
      - name: Set up Actions
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: images/nginx
          platforms: linux/amd64,linux/arm64
          build-args: NGINX_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/rollupdev/nginx:${{ matrix.version }}
